[keys.normal]
k="move_line_down"
j="move_line_up"

[keys.normal.w]
w="rotate_view"
C-w="rotate_view"
v="vsplit_new"
C-v="vsplit"
s="hsplit_new"
C-s="hsplit"
f="goto_file"
F="goto_file"
h="jump_view_left"
C-h="jump_view_left"
"left"="jump_view_left"
C-k="jump_view_down"
k="jump_view_down"
"down"="jump_view_down"
K="swap_view_down"
C-j="jump_view_up"
j="jump_view_up"
"up"="jump_view_up"
J="swap_view_up"
l="jump_view_right"
C-l="jump_view_right"
"right"="jump_view_right"
q="wclose"
C-q="wclose"
o="wonly"
C-o="wonly"
H="swap_view_left"
L="swap_view_right"

[keys.normal.z]
k="scroll_down"
j="scroll_up"

[keys.normal.g]
k="move_line_down"
j="move_line_up"

[editor.cursor-shape]
insert = "bar"
normal = "bar"
select = "underline"
